# Generated by Django 3.2 on 2021-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servantch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionNo', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('typeS', models.CharField(max_length=30)),
                ('flag', models.CharField(max_length=30)),
                ('className', models.CharField(max_length=30)),
                ('attribute', models.CharField(max_length=30)),
                ('rarity', models.CharField(max_length=1)),
                ('atkMax', models.CharField(max_length=5)),
                ('hpMax', models.CharField(max_length=5)),
                ('face', models.CharField(max_length=100)),
            ],
        ),
    ]
