# Generated by Django 3.2 on 2021-04-16 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Servant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servantch',
            name='id',
        ),
        migrations.AddField(
            model_name='servantch',
            name='unique_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
