# Generated by Django 3.2 on 2021-04-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servant', '0002_auto_20210417_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servantch',
            name='unique_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
