# Generated by Django 3.2 on 2021-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servant', '0003_alter_servantch_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='infoCharacter',
            fields=[
                ('unique_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
